version: '2'
services:
  web:
    build: .
    command: python -m playground
    container_name: web
    environment:
      - ENVIRONMENT=DEVELOPMENT
    volumes:
      - .:/code
    ports:
      - '80:8080'
  db:
    container_name: db
    image: postgres:latest
